config:
  backup: true
  banner: true
  create: true
  longkey: true
  chmod_on_import: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  f_i3_config:
    src: i3/config
    dst: ~/.i3/config
    chmod: '644'
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    chmod: '644'
  f_config_nvim_lua_user_init.lua:
    src: config/nvim/lua/user/init.lua
    dst: ~/.config/nvim/lua/user/init.lua
    chmod: '644'
  f_config_polybar_config:
    src: config/polybar/config
    dst: ~/.config/polybar/config
    chmod: '644'
  f_config_polybar_launch.sh:
    src: config/polybar/launch.sh
    dst: ~/.config/polybar/launch.sh
    chmod: '755'
profiles:
  nguyenston:
    dotfiles:
    - f_bashrc
    - f_i3_config
    - f_tmux.conf
    - f_config_nvim_lua_user_init.lua
    - f_config_polybar_config
    - f_config_polybar_launch.sh
